### ISSUE TITLE
Polymath constructor probs don't need OpenAI key

### ISSUE THREAD

**Issue by dglazkov** [polymath-ai/polymath-js-client#13]
If I just want to use the library for querying endpoints, I don't need the OpenAI key. Right?

**Comment by dglazkov** [comment]
ohh `PolymathServer`

**Comment by dalmaer** [comment]
You are right thought. We could consider this optional and only yell when we are doing something with OpenAI.

I want to refactor all of this btw.

library.js
openai.js
pinecone.js

So to speak. It's very much "all in one file hack attack".
